<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="lenovo" name="Default test" tests="2" failures="1" timestamp="28 Oct 2016 20:31:05 GMT" time="40.874" errors="0">
  <testcase name="loginTest" time="21.488" classname="com.qtpselenium.facebook.pom.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="LoginTest failed with the data set -&amp;gt; {Username=savinggrace.456@gmail.com, ExpectedResult=Successful, Password=reset123, Runmode=Y, Browser=Mozilla}">
      <![CDATA[java.lang.AssertionError: LoginTest failed with the data set -> {Username=savinggrace.456@gmail.com, ExpectedResult=Successful, Password=reset123, Runmode=Y, Browser=Mozilla}
	at org.testng.Assert.fail(Assert.java:94)
	at com.qtpselenium.facebook.pom.base.BaseTest.reportFailure(BaseTest.java:68)
	at com.qtpselenium.facebook.pom.testcases.LoginTest.loginTest(LoginTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="loginTest" time="17.915" classname="com.qtpselenium.facebook.pom.testcases.LoginTest"/>
</testsuite> <!-- Default test -->
